---
title: "Centenarians"
author: "fth"
format: gfm
execute: 
  warning: false
---

### loading packages 
```{r setup}
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(lubridate)
library(gt)
library(rvest)

```


### get data 

```{r}
# data loc: 
root <- paste0("https://en.wikipedia.org/wiki/List_of_verified_oldest_people") 
tables <- read_html(root) |> html_nodes("table")

# get data by gender: 
old_women <- tables[[1]] |> 
  html_table(header = TRUE) |>
  mutate(
    gender = 'female'
  )

old_men <- tables[[2]] |> 
  html_table(header = TRUE) |>
  mutate(
    gender = 'male'
  )

```

### wrangling

```{r}
# fix headers: 
cols <- c('rank', 'name', 'birth_date', 'death_date', 'age', 'place_of_death_or_residence', 'gender')

colnames(old_women) <- cols
colnames(old_men)   <- cols

# bind all ppl: 
old_ppl <- old_women |> rbind(old_men)


# remove [reference] indices, fix date coltypes & age calc in year fractions:
old_ppl <-
old_ppl |>
  mutate( # regex
    name = str_replace(name, "\\[.*]", ""),
    birth_date = str_replace(birth_date, "\\[.*]", ""),
    death_date = str_replace(death_date, "\\[.*]", ""),
    place_of_death_or_residence = str_replace(place_of_death_or_residence, "\\[.*]", "")
  ) |>
  mutate( # dates & age formatting
    birth_date = dmy(birth_date),
    death_date = dmy(death_date),
    still_alive = ifelse(is.na(death_date), "alive", "deceased"),
    age  = ifelse(still_alive == "alive", 
                  as.numeric(interval(birth_date, Sys.Date()), 'years'), 
                  as.numeric(interval(birth_date, death_date), 'years'))
    )

```

### eda 


```{r}
old_ppl |>
  ggplot() + 
  geom_point(aes(x = birth_date, y = age, color = place_of_death_or_residence #, shape = still_alive
                 ), size = 5, alpha = .7) + 
  scale_color_viridis_d(option = "A", begin = .2) +
facet_wrap(~gender) + 
  labs(
    title = "Oldest Verified People",
    subtitle = "a breakdown by gender & country",
    x = "Birth Date",
    y = "Age"
  ) + 
  theme_minimal() +
  ggdark::dark_mode() + 
  theme(
    panel.background = element_rect(fill = "grey5", color = "grey5"),
    legend.title = element_blank() #,
#    legend.position = "bottom"
  )

```


```{r}
old_ppl |>
  arrange(desc(age)) |>
  slice(1:20) |>
  select(rank, name, gender, age, place_of_death_or_residence, birth_date) |> 
  rename('place of residence' = 'place_of_death_or_residence',
         'birth date' = 'birth_date') |>
  mutate(
    age = round(age)
  ) |>
  gt() |>
  tab_header(title = md('**Oldest Verified People Dataset**'),
             subtitle = md('top 20 oldest people')) |>
  tab_footnote(
    md("*top 20 oldest people are all female*")
  )
  

```


